cluster_issuers:
  letsencrypt:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: sre@dexfinannce.com
      privateKeySecretRef:
        name: letsencrypt
      solvers:
      - selector:
          dnsZones:
          - "prd.exampleco.com"
        http01:
          ingress:
            ingressClassName: konghq-gcp-prd

cert-manager:
  enabled: true
  nodeSelector:
    apps-spot: "true"
  tolerations:
  - key: "apps-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  cainjector:
    enabled: true
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  webhook:
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
